repos:
  # black code formatter
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        require_serial: true
        args:
          - --exclude=examples/
          
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args:
          - --fix
          - --exclude=examples/
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml

  