import os
import json
from dotenv import load_dotenv
import logging

# Load environment variables from dotenv file if not present in os.environ
if "ENV" in os.environ:
    ENV = os.environ["ENV"]
else:
    logging.info("Using local ENVs.")
    load_dotenv("local_testing/contracts.env")
    ENV = os.environ["ENV"]

# Service URLs
RLEF_URL = os.environ["RLEF_URL"]
COPILOT_URL = os.environ["COPILOT_URL"]
SPT_URL = os.environ["SPT_URL"]

# LLM Models
DOCUMENT_RETRIEVAL_MODEL_ID = os.environ["DOCUMENT_RETRIEVAL_MODEL_ID"]
EVALUATION_MODEL_ID = os.environ["EVALUATION_MODEL_ID"]
BEST_ANSWER_MODEL_ID = os.environ["BEST_ANSWER_MODEL_ID"]

EVALUATION_COPILOT_ID = os.environ["EVALUATION_COPILOT_ID"]
BEST_ANSWER_COPILOT_ID = os.environ["BEST_ANSWER_COPILOT_ID"]

TAG_PREFIX = os.environ["TAG_PREFIX"]

# EMBEDDING MODEL
GOOGLE_EMBEDDING_MODEL = os.environ["GOOGLE_EMBEDDING_MODEL"]  # "textembedding-gecko@002" or "all-MiniLM-L6-v2"

# GCP ENVIRONMENT
FIREBASE_URL = os.environ["FIREBASE_URL"]
PUBSUB_PROJECT_ID = os.environ["PUBSUB_PROJECT_ID"]
PUBSUB_AI_BACKEND_SUBSCRIPTION_ID = os.environ["PUBSUB_AI_BACKEND_SUBSCRIPTION_ID"]
PUBSUB_TOPIC_ID = os.environ["PUBSUB_TOPIC_ID"]
VOICE_REQUEST_TOPIC_ID = os.environ["VOICE_REQUEST_TOPIC_ID"]
VOICE_TRANSCRIPTION_SUBSCRIPTION_ID = os.environ["VOICE_TRANSCRIPTION_SUBSCRIPTION_ID"]
VOICE_PUBSUB_TIMEOUT = int(os.getenv("VOICE_PUBSUB_TIMEOUT", 300))

# COPILOT CONFIGURATION
COPILOT_TIMEOUT = int(os.environ["COPILOT_TIMEOUT"])
COPILOT_THRESHOLD = int(os.environ["COPILOT_THRESHOLD"])
RLEF_COPILOT_THRESHOLD = bool(os.environ["RLEF_COPILOT_THRESHOLD"])

# INDIVIDUAL MODEL THRESHOLD
DEFAULT_INDIVIDUAL_GOOGLE_THRESHOLD = int(os.environ["DEFAULT_INDIVIDUAL_GOOGLE_THRESHOLD"])
DEFAULT_INDIVIDUAL_AZURE_THRESHOLD = int(os.environ["DEFAULT_INDIVIDUAL_AZURE_THRESHOLD"])

PUBSUB_TIMEOUT = int(os.environ["PUBSUB_TIMEOUT"])

# Default message for no matches
DEFAULT_MESSAGE = os.environ["DEFAULT_MESSAGE"]

# AZURE OPENAI ENVIRONMENT
AZURE_API_TYPE = os.environ["AZURE_API_TYPE"]
AZURE_API_BASE = os.environ["AZURE_API_BASE"]
AZURE_API_VERSION = os.environ["AZURE_API_VERSION"]
AZURE_OPENAI_API_KEY = os.environ["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_ENDPOINT = os.environ["AZURE_OPENAI_ENDPOINT"]

DALLE_AZURE_API_VERSION = os.environ["DALLE_AZURE_API_VERSION"]
DALLE_AZURE_OPENAI_API_KEY = os.environ["DALLE_AZURE_OPENAI_API_KEY"]
DALLE_AZURE_OPENAI_ENDPOINT = os.environ["DALLE_AZURE_OPENAI_ENDPOINT"]

# DATA LAKE ENVIRONMENT
DATA_LAKE_ACCOUNT_NAME = os.environ["DATA_LAKE_ACCOUNT_NAME"]
DATA_LAKE_ACCOUNT_KEY = os.environ["DATA_LAKE_ACCOUNT_KEY"]
DATA_LAKE_FILE_SYSTEM_NAME = os.environ["DATA_LAKE_FILE_SYSTEM_NAME"]

# SWAGGER UI
SWAGGER_URL = '/api/docs'
API_URL = '/static/swagger.json'

# OPENSOURCE Model
OPENSOURCE_URL = os.environ["OPENSOURCE_URL"]

# Tokens cost file
COST_FILE = "utils/model_costs.json"

# AlloyDB Configuration
DB_NAME = os.environ["DB_NAME"]
DB_USER = os.environ["DB_USER"]
DB_PASS = os.environ["DB_PASS"]
DB_HOST = os.environ["DB_HOST"]
DB_PORT = os.environ["DB_PORT"]

# PROPOSALS
PROPOSALS_BUCKET_NAME = os.environ["PROPOSALS_BUCKET_NAME"]
PROPOSALS_EMAIL_SENDER = os.environ["PROPOSALS_EMAIL_SENDER"]
PROPOSALS_EMAIL_TOKEN = os.environ["PROPOSALS_EMAIL_TOKEN"]

# VISION INTEGRATION
IMAGES_BUCKET_NAME = os.environ["IMAGES_BUCKET_NAME"]

# SHAREPOINT
SHAREPOINT_TENANT_ID = os.environ["SHAREPOINT_TENANT_ID"]
SHAREPOINT_CLIENT_ID = os.environ["SHAREPOINT_CLIENT_ID"]
SHAREPOINT_CLIENT_SECRET = os.environ["SHAREPOINT_CLIENT_SECRET"]

# MONGO
MONGO_URL = os.environ["MONGO_URL"]

# BASE URLs
BACKEND_BASE_URL = os.environ["BACKEND_BASE_URL"]
COPILOT_UI_URL = os.environ["COPILOT_UI_URL"]

# OpenAI Client key
OPENAI_KEY = os.environ["OPENAI_KEY"]

# INTERNET SEARCH TAVILY API KEY
TAVILY_API_KEY = os.environ['TAVILY_API_KEY']

# GITHUB_INGESTION
PUBSUB_GITHUB_BATCH_INTERVAL = int(os.environ["PUBSUB_GITHUB_BATCH_INTERVAL"])
PUBSUB_GITHUB_BATCH_SIZE = int(os.environ["PUBSUB_GITHUB_BATCH_SIZE"])

# LLM_CRAWLER
WEB_CRAWLER_CLOUD_FUNCTION_URL = os.environ["WEB_CRAWLER_CLOUD_FUNCTION_URL"]
FIREBASE_LOG_URL = os.environ["FIREBASE_LOG_URL"]
BIGQUERY_DATASET = os.environ["BIGQUERY_DATASET"]

# AGENTS
MAX_ITERATIONS_WITH_AGENTS = int(os.getenv("MAX_ITERATIONS_WITH_AGENTS", 12))
AGENTS_PUBLISH_QUERY_TOPIC_ID = os.environ["AGENTS_PUBLISH_QUERY_TOPIC_ID"]
AGENTS_RECEIVE_RESPONSE_SUBSCRIPTION_ID = os.environ["AGENTS_RECEIVE_RESPONSE_SUBSCRIPTION_ID"]

# NODE.JS CALL FOR CHAT HISTORY
EGPT_NODE_BASE_URL = os.environ["EGPT_NODE_BASE_URL"]

# FOR EMBEDDING
EMBEDDING_SERVICE = os.environ["EMBEDDING_SERVICE"]
CRYPTO_SECRET = os.environ["CRYPTO_SECRET"]

# CONTEXT-AWARE-CHAT-HISTORY-SEARCH
MONGODB_NAME = os.environ["MONGODB_NAME"]
MONGODB_CHAT_HISTORY_GRAPH_COLLECTION_NAME = os.environ["MONGODB_CHAT_HISTORY_GRAPH_COLLECTION_NAME"]
MONGODB_CHAT_HISTORY_GRAPH_NODES_COLLECTION_NAME = os.environ["MONGODB_CHAT_HISTORY_GRAPH_NODES_COLLECTION_NAME"]
MONGODB_CHAT_HISTORY_GRAPH_LINKS_COLLECTION_NAME = os.environ["MONGODB_CHAT_HISTORY_GRAPH_LINKS_COLLECTION_NAME"]

# REDIS
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
REDIS_DB = os.environ["REDIS_DB"]
REDIS_PASSWORD = os.environ["REDIS_PASSWORD"]

# Server's PubSub configs
MAX_WORKER_THREADS = int(os.environ.get('MAX_WORKER_THREADS', 10))
MAX_MESSAGES = int(os.environ.get('MAX_MESSAGES', MAX_WORKER_THREADS))
MAX_PUBSUB_BYTES = int(os.environ.get('MAX_PUBSUB_BYTES', 104857600))  # 100 MB
MAX_SUBSCRIBER_WORKER_THREADS = int(os.environ.get('MAX_SUBSCRIBER_WORKER_THREADS', 10))

# Worker configuration for Gunicorn
WORKER_COUNT = int(os.environ.get('WORKER_COUNT', 4))
WORKER_TIMEOUT = int(os.environ.get('WORKER_TIMEOUT', 300))
WORKER_THREADS_COUNT = int(os.environ.get('WORKER_THREADS_COUNT', 2))
WORKER_GRACEFUL_TIMEOUT = int(os.environ.get('WORKER_GRACEFUL_TIMEOUT', 30))
MAX_REQUEST_TO_WORKER_RESTART = int(os.environ.get('MAX_REQUEST_TO_WORKER_RESTART', 1000))

# Organization configuration
ORGANIZATION_NAME = os.getenv("ORGANIZATION_NAME", "techolution")
NODE_AUTH_TOKEN = os.getenv('NODE_AUTH_TOKEN', None)
