# Test for issue #2349: BUG: Broken Space runtime in tools.md documentation example
# Auto-generated by PR Harness

import pytest


def test_issue_2349():
    """Regression test for issue #2349."""
    # TODO: implement proper test reproduction
    # Issue: BUG: Broken Space runtime in tools.md documentation example
    pass

