# Test for issue #2365: BUG: ActionStep 的 observations 也应该是一个 list
# Auto-generated by PR Harness

import pytest


def test_issue_2365():
    """Regression test for issue #2365."""
    # TODO: implement proper test reproduction
    # Issue: BUG: ActionStep 的 observations 也应该是一个 list
    pass

