from pathlib import Path
import os

PROMPTS_DIR = os.getenv('CUSTOM_PROMPTS_DIR', Path(__file__).parent / "PROMPTS")

def _load_prompt(name: str) -> str:
    with open(f"{PROMPTS_DIR}/{name}.config", "r", encoding="utf-8") as f:
        return f.read()

# Load all prompts
SINGLE_STEP_CODE_SYSTEM_PROMPT = _load_prompt("SINGLE_STEP_CODE_SYSTEM_PROMPT")
TOOL_CALLING_SYSTEM_PROMPT = _load_prompt("TOOL_CALLING_SYSTEM_PROMPT")
CODE_SYSTEM_PROMPT = _load_prompt("CODE_SYSTEM_PROMPT")
SYSTEM_PROMPT_FACTS = _load_prompt("SYSTEM_PROMPT_FACTS")
SYSTEM_PROMPT_PLAN = _load_prompt("SYSTEM_PROMPT_PLAN")
USER_PROMPT_PLAN = _load_prompt("USER_PROMPT_PLAN")
SYSTEM_PROMPT_FACTS_UPDATE = _load_prompt("SYSTEM_PROMPT_FACTS_UPDATE")
USER_PROMPT_FACTS_UPDATE = _load_prompt("USER_PROMPT_FACTS_UPDATE")
SYSTEM_PROMPT_PLAN_UPDATE = _load_prompt("SYSTEM_PROMPT_PLAN_UPDATE")
USER_PROMPT_PLAN_UPDATE = _load_prompt("USER_PROMPT_PLAN_UPDATE")
PLAN_UPDATE_FINAL_PLAN_REDACTION = _load_prompt("PLAN_UPDATE_FINAL_PLAN_REDACTION")
MANAGED_AGENT_PROMPT = _load_prompt("MANAGED_AGENT_PROMPT")

__all__ = [
    "USER_PROMPT_PLAN_UPDATE",
    "PLAN_UPDATE_FINAL_PLAN_REDACTION", 
    "SINGLE_STEP_CODE_SYSTEM_PROMPT",
    "CODE_SYSTEM_PROMPT",
    "TOOL_CALLING_SYSTEM_PROMPT",
    "MANAGED_AGENT_PROMPT",
]
